"""PDF medical report generation using ReportLab."""

import os
from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage,
)

from app.config import get_settings

settings = get_settings()


def generate_report(
    scan_id: int,
    patient_name: str,
    image_path: str,
    prediction: str,
    confidence: float,
    probabilities: dict,
) -> str:
    """Generate a professional PDF medical report and return the file path."""
    os.makedirs(settings.REPORTS_DIR, exist_ok=True)
    filename = f"report_{scan_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(settings.REPORTS_DIR, filename)

    doc = SimpleDocTemplate(filepath, pagesize=A4,
                            topMargin=20*mm, bottomMargin=20*mm,
                            leftMargin=20*mm, rightMargin=20*mm)
    styles = getSampleStyleSheet()
    elements = []

    # --- Custom styles ---
    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"],
        fontSize=22, textColor=colors.HexColor("#1e40af"),
        spaceAfter=6*mm,
    )
    heading_style = ParagraphStyle(
        "SectionHeading", parent=styles["Heading2"],
        fontSize=14, textColor=colors.HexColor("#1e3a5f"),
        spaceBefore=6*mm, spaceAfter=3*mm,
    )
    normal = styles["Normal"]

    # --- Header ---
    elements.append(Paragraph("MedPredict AI — Diagnostic Report", title_style))
    elements.append(Paragraph(
        f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        normal,
    ))
    elements.append(Spacer(1, 4*mm))

    # --- Patient info ---
    elements.append(Paragraph("Patient Information", heading_style))
    info_data = [
        ["Patient Name:", patient_name],
        ["Report ID:", f"MED-{scan_id:06d}"],
        ["Scan Type:", "Brain MRI"],
        ["Analysis Engine:", "MedPredict AI v2.0 — Swin Transformer"],
    ]
    info_table = Table(info_data, colWidths=[45*mm, 110*mm])
    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eff6ff")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(info_table)
    elements.append(Spacer(1, 4*mm))

    # --- MRI thumbnail ---
    if Path(image_path).exists():
        elements.append(Paragraph("Uploaded MRI Scan", heading_style))
        try:
            img = RLImage(image_path, width=60*mm, height=60*mm)
            elements.append(img)
        except Exception:
            elements.append(Paragraph("[Image could not be embedded]", normal))
        elements.append(Spacer(1, 4*mm))

    # --- Prediction result ---
    is_cancer = prediction != "No Tumor"
    result_color = "#dc2626" if is_cancer else "#16a34a"
    elements.append(Paragraph("Diagnosis Result", heading_style))
    elements.append(Paragraph(
        f'<font color="{result_color}" size="16"><b>{prediction}</b></font>',
        normal,
    ))
    elements.append(Paragraph(
        f"Confidence: <b>{confidence * 100:.1f}%</b>", normal,
    ))
    elements.append(Spacer(1, 3*mm))

    # --- Probability table ---
    elements.append(Paragraph("Class Probabilities", heading_style))
    prob_header = ["Class", "Probability"]
    prob_rows = [[cls, f"{prob * 100:.2f}%"] for cls, prob in probabilities.items()]
    prob_table = Table([prob_header] + prob_rows, colWidths=[70*mm, 50*mm])
    prob_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e40af")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(prob_table)
    elements.append(Spacer(1, 6*mm))

    # --- Disclaimer ---
    elements.append(Paragraph("Disclaimer", heading_style))
    elements.append(Paragraph(
        "This report is generated by an AI-based diagnostic tool and is intended "
        "for informational purposes only. It does not constitute a medical diagnosis. "
        "Please consult a qualified healthcare professional for clinical decisions.",
        ParagraphStyle("Disclaimer", parent=normal, fontSize=9,
                       textColor=colors.HexColor("#6b7280")),
    ))

    doc.build(elements)
    return filepath
